# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "People"
  url = "/People"
  weight = 20

[[main]]
  name = "Standards"
  url = "/Standards"
  identifier = "standards"
  weight = 30


[[main]]
  name = "Events"
  url = "/events"
  weight = 50
  identifier = "events"

  [[main]]
  name = "Documents"
  url = "/documents"
  weight = 60
  identifier = "documents"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
